version: 2.1 
orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - salesforce-sfdx/auth:
          defaultdevhubusername: david@mcga.de 
          defaultusername: sc-pkg-dev-org 

workflows:
  example-workflow:
    jobs:
      - example-job