
version: 2.1
orbs:
  apex: circleci/salesforce-apex@1.0.1

jobs:
  install_authenticate:
    docker:
      - image: cimg/node:14.5
    steps:
      - checkout
      - apex/setup:
          defaultusername: user@email.com
      - run:
          name: Run your SFDX commands here
          command: |
            echo "You now have access to the sfdx cli and may execute commands against it. https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm"
workflows:
  basic-test:
    jobs:
      - install_authenticate