version: 2.1

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0

jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: david@mcga.de

      - restore_cache:
          key: -v1-{{ checksum "tests/authOrgs.json" }}
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.

            sfdx auth:list > tests/authOrgs.json
          name: Run your SFDX commands here
      - save_cache:
          key: -v1-{{ checksum "tests/authOrgs.json" }}
          paths:
            - "tests"
  
  create_scratch_org:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: david@mcga.de
      - run:
          command: >
            ./scripts/deployment/createNewScratchOrg.sh sc-pkg-test 
          name: creating scratch org
      - run:
          command: >
            sfdx force:org:display -u sc-pkg-test --verbose
          name: print VERBOSE org details
          
workflows:
  basic-test:
    jobs:
      - install_authenticate
#      - create_scratch_org
