
version: 2.1
orbs:
  sfdx: circleci/salesforce-sfdx@2.1

jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - sfdx/auth:
          defaultusername: david@mcga.de

workflows:
  basic-test:
    jobs:
      - install_authenticate
