version: 2.1

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0

jobs:
  set-up-enviroment:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install

      # install / restore node modules - Start          		
      - restore_cache:
          key: -v1-node_modules

      - run:
          command: >
            npm install sfdx-node
          name: install sfdx-node

      # install / restore node modules - End		
      - save_cache:
          key: -v1-node_modules
          paths:
            - "node_modules"
      - run:
          command: |
            mkdir tmp
            mkdir tmp/artifacts
            mkdir tmp/cache
          name: create folder for artifacts 
      - run:
          command: |
            chmod +x scripts/deployment/*
          name: make scripts executable 

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ./
          # Must be relative path from root
          paths:
            - ./

  create-cache-checksum:
    executor: sfdx/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
          
      - run:
          command: >
            node ./scripts/deployment/node/writeChecksumFile.js
          name: writing file for checksum

      - persist_to_workspace:
          root: ./
          paths:
            - ./
            
            
  print-org-limits:
    executor: sfdx/default
    parameters:
      filename:
        type: string
    steps:
      - sfdx/install
      - sfdx/auth:
          defaultusername: david@mcga.de
      - run:
          command: >
            sfdx force:limits:api:display -u david@mcga.de > << parameters.filename >>
          name: print org limits
      - store_artifacts:
          path: << parameters.filename >>


  create-scratch-org:
    executor: sfdx/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./

      - run:
          command: |
            pwd
            ls -la
          name: print Filesystem

      - sfdx/install

      - run:
          command: |
            pwd
            ls -la > tmp/artifacts/beforeCache-ls-root.txt
            ls -la tmp/ > tmp/artifacts/beforeCache-ls-tmp.txt
            ls -la tmp/cache/ > tmp/artifacts/beforeCache-ls-cache.txt
          name: print Filesystem before cache

      - sfdx/auth:
          defaultusername: david@mcga.de

      - run:
          command: >
            sfdx force:limits:api:display -u david@mcga.de > tmp/artifacts/limitsBefore.txt
          name: print org limits before creation

  # create / restore credential file
    # chaching - start
      - restore_cache:
          name: Restore cached org credentials
          keys: 
            - -v7-credentials-{{ checksum "checksum_24h.cache" }}

      - run:
          command: |
            pwd
            ls -la > tmp/artifacts/beforeScratch-ls-root.txt
            ls -la tmp/ > tmp/artifacts/beforeScratch-ls-tmp.txt
            ls -la tmp/cache/ > tmp/artifacts/beforeScratch-ls-cache.txt
          name: print Filesystem before scratch org

      - run:
          command: |
            scripts/deployment/createNewScratchOrg.sh testScratchOrg tmp/cache/authFile.json
            base64 tmp/cache/authFile.json > tmp/cache/base64AuthFile
          name: create scratch org

      - save_cache:
          name: Save cached org credentials
          key: -v7-credentials-{{ checksum "checksum_24h.cache" }}
          paths:
            - ./tmp/cache/base64AuthFile
       # chaching scratch org credentials - end 
        
      - run:
          command: |
            pwd
            ls -la > tmp/artifacts/afterCache-ls-root.txt
            ls -la tmp/ > tmp/artifacts/afterCache-ls-tmp.txt
            ls -la tmp/cache/ > tmp/artifacts/afterCache-ls-cache.txt
          name: print Filesystem after cache

      - run:
          command: >
            sfdx force:limits:api:display -u david@mcga.de > tmp/artifacts/limitsAfter.txt
          name: print org limits after creation

      - store_artifacts:
          path: tmp/artifacts/
      
      - store_artifacts:
          path: tmp/cache/authFile.json

      - store_artifacts:
          path: ./tmp/cache/base64AuthFile
          
      - run:
          command: >
            rm server.key
          name: Remove 'server.key' file
      
      - persist_to_workspace:
          root: ./
          paths:
            - ./
    

  push-code-and-run-tests:
    executor: sfdx/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ./
          
      - sfdx/install
      - sfdx/auth:
          defaultusername: david@mcga.de

      - restore_cache:
          name: Restore cached org credentials
          keys: 
            - -v7-credentials-{{ checksum "checksum_24h.cache" }}
          
      - run:
          command: |      
            base64 --decode ./tmp/cache/base64AuthFile > ./tmp/cache/authFile.json
          name: Decode authfile

      - run:
          command: |
            pwd
            ls -la > tmp/artifacts/push-ls-root.txt
            ls -la tmp/ > tmp/artifacts/push-ls-tmp.txt
            ls -la tmp/cache/ > tmp/artifacts/push-ls-cache.txt
          name: print Filesystem
          
      - store_artifacts:
          path: tmp/cache/authFile.json
          
      - run:
          command: >
            scripts/deployment/authorizeWithAuthFile.sh tempScratchOrg tmp/cache/authFile.json
          name: authorize via AuthFile

      - run:
          command: >
            sfdx force:source:push --targetusername tempScratchOrg --forceoverwrite --wait 60 > tmp/artifacts/DeploymentResults.txt
          name: SFDX Push Changes
          
      - run:
          command: >
            sfdx force:apex:test:run --targetusername tempScratchOrg --suitenames=MapUtilities --resultformat=human --codecoverage --wait 60 > tmp/artifacts/testResults.txt
          name: Run APEX Tests

      - run:
          command: >
            sfdx force:limits:api:display -u david@mcga.de > tmp/artifacts/limitsAfter.txt
          name: print org limits

      - store_artifacts:
          path: tmp/artifacts/          


workflows:
  test-limit-print:
    jobs:
      - print-org-limits:
          filename: orgLimits.txt
      - print-org-limits:
          filename: orgLimits2.txt

  # basic-test:
  #   jobs:
  #     - set-up-enviroment
  #     - create-cache-checksum:
  #         requires:
  #           - set-up-enviroment
  #     - create-scratch-org:
  #         requires:
  #           - set-up-enviroment
  #           - create-cache-checksum
  #         filters:
  #           branches:
  #             ignore: master
  #     - push-code-and-run-tests:
  #         requires:
  #           - create-scratch-org
